#ifndef TOPAZ_ERRNO_H
#define TOPAZ_ERRNO_H

/*
 * Topaz - Error Numbers / Ids
 *
 * This file implements known error codes, as used by the topaz library.
 *
 * Copyright (c) 2016, T Parys
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer. 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/** General topaz error number of type uint32_t */
typedef enum
{
/* === BEGIN AUTOGENERATED CONTENT === */

  /** No error reported */
  TP_ERR_SUCCESS         = 0x00000000,

  /** Unspecified error */
  TP_ERR_UNSPECIFIED     = 0x00000001,

  /** Error opening file */
  TP_ERR_OPEN            = 0x00000002,

  /** Error opening file */
  TP_ERR_CLOSE           = 0x00000003,

  /** Invalid argument */
  TP_ERR_INVALID         = 0x00000004,

  /** NULL Pointer */
  TP_ERR_NULL            = 0x00000005,

  /** Error allocating memory */
  TP_ERR_ALLOC           = 0x00000006,

/* TPM Errors */

  /** Target drive does not contain a TPM */
  TP_ERR_NO_TPM          = 0x00010000,

  /** TPM does not support a known protocol */
  TP_ERR_TPM_PROTO       = 0x00010001,

  /** TPM using an unknown protocol version */
  TP_ERR_TPM_VERSION     = 0x00010002,

  /** Unrecognized SSC messaging type */
  TP_ERR_TPM_SSC         = 0x00010003,

  /** Cannot reset specified ComID */
  TP_ERR_TPM_COMID_RESET = 0x00010004,

/* Tranport Errors */

  /** Failed to call ioctl */
  TP_ERR_IOCTL           = 0x00020000,

  /** Bad sense data */
  TP_ERR_SENSE           = 0x00020001,

/* Linux Specific Errors */

  /** Error reading from sysfs */
  TP_ERR_SYSFS           = 0x00030000,

  /** Libata blocking TPM calls (add kernel argument 'libata.allow_tpm=1') */
  TP_ERR_LIBATA          = 0x00030001,


/* === END AUTOGENERATED CONTENT === */
} tp_errno_t;

/** Last topaz error number */
tp_errno_t tp_errno;

/**
 * \brief Error Number String Lookup (Current)
 *
 * Returns a human readable interpretation of the current Topaz error code
 *
 * \param[in] id Valid error identifier
 * \return Pointer to static buffer containing error message
 */
char const *tp_errno_lookup_cur();

/**
 * \brief Error Number String Lookup (Arbitrary)
 *
 * Returns a human readable interpretation of a arbitrary Topaz error code
 *
 * \param[in] id Valid error identifier
 * \return Pointer to static buffer containing error message
 */
char const *tp_errno_lookup(tp_errno_t id);

#endif
