/*
 * Topaz - Error Numbers / Ids
 *
 * This file implements known error codes, as used by the topaz library.
 *
 * Copyright (c) 2016, T Parys
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer. 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <topaz/errno.h>

/** Last topaz error number */
unsigned int tp_errno = 0;

/** Structure to store error messages */
typedef struct
{
  unsigned int id;
  char const *msg;
} tp_errno_entry_t;  

/** Known topaz error codes */
tp_errno_entry_t tp_errno_db[] =
{
/* === BEGIN AUTOGENERATED CONTENT === */

  /* TP_ERR_SUCCESS         */ { 0x00000000, "No error reported" },
  /* TP_ERR_UNSPECIFIED     */ { 0x00000001, "Unspecified error" },
  /* TP_ERR_OPEN            */ { 0x00000002, "Error opening file" },
  /* TP_ERR_CLOSE           */ { 0x00000003, "Error opening file" },
  /* TP_ERR_INVALID         */ { 0x00000004, "Invalid argument" },
  /* TP_ERR_NULL            */ { 0x00000005, "NULL Pointer" },
  /* TP_ERR_ALLOC           */ { 0x00000006, "Error allocating memory" },

  /* Tranport Errors */

  /* TP_ERR_IOCTL           */ { 0x00001000, "Failed to call ioctl" },
  /* TP_ERR_SENSE           */ { 0x00001001, "Bad sense data" },

  /* Linux Specific Errors */

  /* TP_ERR_SYSFS           */ { 0x00002000, "Error reading from sysfs" },
  /* TP_ERR_LIBATA          */ { 0x00002001, "Libata blocking TPM calls (add kernel argument 'libata.allow_tpm=1')" },

/* === END AUTOGENERATED CONTENT === */
};

/**
 * \brief Error Number String Lookup (Current)
 *
 * Returns a human readable interpretation of the current Topaz error code
 *
 * \param[in] id Valid error identifier
 * \return Pointer to static buffer containing error message, or NULL on error
 */
char const *tp_errno_lookup_cur()
{
  return tp_errno_lookup(tp_errno);
}

/**
 * \brief Error Number String Lookup (Arbitrary)
 *
 * Returns a human readable interpretation of a arbitrary Topaz error code
 *
 * \param[in] id Valid error identifier
 * \return Pointer to static buffer containing error message, or NULL on error
 */
char const *tp_errno_lookup(unsigned int id)
{
  unsigned int db_size = sizeof(tp_errno_db) / sizeof(tp_errno_entry_t);
  unsigned int i;
  
  /* Look for matching ID */
  for (i = 0; i < db_size; i++)
  {
    if (tp_errno_db[i].id == id)
    {
      return tp_errno_db[i].msg;
    }
  }
  
  /* Did not find it */
  return "Invalid topaz errno";
}
